### ISSUE TITLE
Graceful disconnects, timeouts and reconnection

### ISSUE THREAD

**Issue by blakejakopovic** [peterschwarz/clj-firmata#12]
Presently, any interruption of a serial connection (which basically means it has been physically disconnected), results in the following exception.
>Exception in thread "tty.usbmodemfd1231" java.io.IOException
	at purejavacomm.PureJavaSerialPort$2.read(PureJavaSerialPort.java:924)
	at purejavacomm.PureJavaSerialPort$2.read(PureJavaSerialPort.java:734)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:313)
	at firmata.core$read_event.invoke(core.clj:291)
	at firmata.core$firmata_handler$fn__11185.invoke(core.clj:306)
	at serial.core$listen$reify__10820.serialEvent(core.clj:117)

And while in this case, I believe a patch is required for [peterschwarz/clj-serial](https://github.com/peterschwarz/clj-serial) to add exception handling, I think that we also need a way to handle disconnects and timeouts in `clj-firmata`. Exception handling will also be important in the case of using `TCP` and network adapters, which are far more unreliable.

I am not sure if it would be best to include a reconnection mode mechanism into `cli-firmata`, or let library users handle it. My main concern would be that if a dropout occurs, could data-loss occur, and would the library user be able to detect it. In some cases, such as `UDP` it wouldn't matter, as well as some user applications - however, I am not sure if data-loss in some applications would be unacceptable (for example some kind of atomic counter, or statistic aggregation).

A reconnection would only apply to certain adapters (eg. `SerialStream` and `SocketStream`), as any host `clj-firmata` stream would require the Arduino clients to handle disconnections, reconnections and timeouts themselves. But the server adapters should support disconnection and timeouts of clients - for instance, so they can update the UI.

Perhaps the `FirmataStream` protocol should support a `reconnect` method, however, I am not sure how best to implement all three (disconnect, timeout and reconnection) cases.

**Comment by peterschwarz** [comment]
Progress made on this front: 

* https://github.com/peterschwarz/clj-firmata/commit/14540009798472d0e808e5b353d16598a72ccbd3
* https://github.com/peterschwarz/clj-firmata/commit/d0300b3822d0a189c6d68e9aa6d61979625ac262
* https://github.com/peterschwarz/clj-firmata/commit/2243185e77b28778282508c5be94b7e42d59af74

**Comment by peterschwarz** [comment]
I've fixed this by forwarding the exceptions on the read channel, and all it's multiplexed areas.  

As far as reconnection goes, It's up to the library user to determine when and how they reconnect.  

Biggest change, though backward compatible is using a channel for digital and analog events.  For example:

```
(let [board (open-board ...)
        alg-ch (analog-event-chan board 0)]
  (go-loop [evt (<! alg-ch)] 
    ; .. do what you like
    ))
```

**Comment by peterschwarz** [comment]
Currently deployed on clojars in `[clj-firmata "2.0.2-SNAPSHOT"]`

**Comment by blakejakopovic** [comment]
Awesome. Thanks heaps for working on this. When I get some time I'll test it out, and report any issues.
