### ISSUE TITLE
Serial connection on Linux not working

### ISSUE THREAD

**Issue by metasoarous** [peterschwarz/clj-firmata#26]
I'm getting the following error after trying to run `(open-serial-board :auto-detect)` or `(open-serial-board "/dev/ttyACM0")` (and various mungings thereof):

    CompilerException java.lang.UnsatisfiedLinkError: Can't obtain updateLastError method for class com.sun.jna.Native, compiling:(form-init2664821759257252675.clj:1:12)

Subsequence attempts to connect give:

    CompilerException java.lang.NoClassDefFoundError: Could not initialize class jtermios.JTermios, compiling:(form-init8152663158610466294.clj:1:12) 

Any idea what I might want to look for in getting things working here? I'm on Ubuntu 14.10, and my board connection seems to be working just fine (pushing sketches and such).

**Comment by metasoarous** [comment]
I discovered by looking at [clodiuno](https://github.com/nakkaya/clodiuno) that I just needed to set the correct system property `(System/setProperty "gnu.io.rxtx.SerialPorts" "/dev/ttyACM0")`. Then both setting directly and using `:auto-detect` work great then. However, it wasn't immediately obvious that I should use `ttyACM0` to connect directly instead of `/dev/ttyACM0`. Some extra documentation around all this would be much appreciated.

**Comment by peterschwarz** [comment]
Which jvm are you using?  I'll have to test it again on linux, just to see.  I think I tested it using a VM, so I'm not sure what settings I had used.

**Comment by peterschwarz** [comment]
Just another thought about the fix you mentioned:

`(System/setProperty "gnu.io.rxtx.SerialPorts" "/dev/ttyACM0")` is for a different underlying serial library ([serial-port](https://github.com/samaaron/serial-port) vs [clj-serial](https://github.com/peterschwarz/clj-serial)) which uses native code for its serial communication.  I'm not sure that had anything to do with your issue.

Still, I'll have to setup a test for it.

**Comment by peterschwarz** [comment]
I haven't been able to reproduce this on Xubuntu 15.04.  

I think the underlying java library is not requiring the `/dev/` portion of the name string.  I can add it to the documentation, but I should also have the serial library deal with that sort of thing

**Comment by peterschwarz** [comment]
I've updated the underlying serial library, which now accepts both full paths and names of ports (e.g. `/dev/ttyACM0` and `ttyACM0`).

It should be part of the snapshot.

**Comment by metasoarous** [comment]
Wonderful! Thanks!
